export const LANGUAGES = {
  'en-EN': {
    placeholder: 'Search a movie',
    upcomingTitle: 'New releases',
    movieRelease: 'Release date',
    movieRating: 'Rating',
    vote: 'Vote count',
    castTitle: 'Cast',
    birthDate: 'Birth date',
    place: 'Birth place',
    death: 'Death date',
    bio: 'Biography',
    error: 'Error',
    errorRedirection: 'Return to home page :)',
  },
  'fr-FR': {
    placeholder: 'Recherchez un film',
    upcomingTitle: 'Dernières sorties',
    movieRelease: 'Date de sortie',
    movieRating: 'Note',
    vote: 'Nb de votes',
    castTitle: 'Distribution',
    birthDate: 'Date de naissance',
    place: 'Lieu de naissance',
    death: 'Date de décès',
    bio: 'Biographie',
    error: 'Erreur',
    errorRedirection: "Retour à la page d'accueil :)",
  },
};
